### ISSUE TITLE
Access Violation: Error Code 0xc0000005

### ISSUE THREAD

**Issue by GabRioBlu** [absoIute/Mega-Hack-Extensions#3]
Here is some info from the crashlogs:
Code: Access Violation (0xc0000005)
Fault Address: 792C2BB2
Fault Module: hackpro.dll
Fault Offset: 00082BB2

Stack Walk:
hackpro.dll + 00082BB2
MG6Learning.dll + 00001421
KERNEL32.DLL + 0001FA29
ntdll.dll + 00067A9E
ntdll.dll + 00067A6E
(MG6Learning is my custom hack)

I used ghidra to try and find 00001421 in my extension, and commented out around the error, and tried again.
Basically, it's the custom Initialise function in the extension class. It does not seem to like me trying to add textboxes and check boxes and stuff. I tried not adding any boxes, and just commiting it, and it came SO CLOSE TO LOADING THE GAME. I mean that it opened the exe, showed the game window, loaded the bar until it was at about 90%, then crashed.

Crashlog:

Code: Access Violation (0xc0000005)
Fault Address: 79315075
Fault Module: hackpro.dll
Fault Offset: 000D5075

Stack Walk:
hackpro.dll + 000D5075
hackpro.dll + 000A6A38
hackpro.dll + 000A73DD
hackpro.dll + 000D1DA0
gdi32full.dll + 00087ACB
libcocos2d.dll + 00114232
libcocos2d.dll + 000C48C0
libcocos2d.dll + 000FFB2D
GeometryDash.exe + 00261175
GeometryDash.exe + 002621FD
KERNEL32.DLL + 0001FA29
ntdll.dll + 00067A9E
ntdll.dll + 00067A6E

No more MG6Learning.dll in there, because the error didn't directly come from my extension, more likely Mega Hack v6 trying to load it, and failing, probably because the window is empty or something?

So the main problem is essentially that Mega Hack will not add boxes to my window, or there will be Access Violation, and if I relent and not add anything, it complains because... I don't have any boxes...? ... And get an Access Violation. so idk what to do.

I'll update after further investigation, next is probably to check hackpro.dll.

Update 1:
Turns out if I comment everything in the Initialise function, the game opens fine. But if I uncomment just creating a textbox, without commiting the window, it still crashes. :P.

**Comment by absoIute** [comment]
send the code!

**Comment by absoIute** [comment]
(very old oops)
