### ISSUE TITLE
How Do I Get The "extensions2" File?

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Extensions#6]
How do I get the file, if there is any file? There is no download for the file itself.

**Comment by absoIute** [comment]
It's in the include folder, download the entire zip & get it from there or just copy paste the code from GitHub

**Comment by BrownieGamingX5** [comment]
![image](https://user-images.githubusercontent.com/60493629/149052906-96388614-2fa1-4d5e-8c0b-8895b2589333.png)

where is the zip file bc i dont see it

**Comment by absoIute** [comment]
![image](https://user-images.githubusercontent.com/20018119/153835901-ee296de7-858a-404b-b1a6-e816acd32fbe.png)
